### ISSUE TITLE
Reducing multiple values

### ISSUE THREAD

**Issue by gordonwoodhull** [crossfilter/reductio#1]
Hi Ethan.  Have you thought about reducing multiple different (unrelated) values?  This is a common requirement for dc.js, e.g. for assigning another aesthetic to another value, like color and radius for a scatter/bubble plot. 

(Out of scope: nesting/pivot/series type things - not talking about multiple keys but multiple values.)

**Comment by r4j4h** [comment]
So far from my testing it is working great!! :+1:  Excellent job!

**Comment by esjewett** [comment]
Excellent - thanks for testing it out and letting me know!
