### ISSUE TITLE
d3 format '.2f' sum precision

### ISSUE THREAD

**Issue by mukherjeea** [crossfilter/reductio#37]
Hi,

I have an attribute amount which I'm converting into `d3.format('.2f')`. In the reductio reducer  the sum accessor is 
`function(d) { return +d.amount; }`
I am expecting a sum amount that is also in '.2f' format but in one of the cases I see more than 2 decimal places.
`Object { =4,  sum=396.54999999999995}`

The summed amounts are as follows
`346.5, 15.4, 19.25, 15.4`

I was expecting a `396.55`

What is the reason behind this behaviour?

Thanks

**Comment by esjewett** [comment]
d3.format returns strings. The sum accessor then converts these strings back into numbers to sum them and I assume they suffer from float point precision errors. The solution is to use d3.format before displaying the results, not on your original data.

**Comment by mukherjeea** [comment]
Thanks!
