### ISSUE TITLE
Setting a group's order method

### ISSUE THREAD

**Issue by mukherjeea** [crossfilter/reductio#46]
I am trying to use post to cap the keys but I am not able to make sense of the following in the README.

> It might be wise to set your groups `order` method before using this.

I usually follow this
`barGroup=reductio().count(true).sum('foo')(barDim.group())` 

Could someone please elaborate on this? How should I go about this?

**Comment by esjewett** [comment]
I've updated the documentation to clarify that this means the order method on the Crossfilter group itself, not in Reductio.
