### ISSUE TITLE
complete groupAll example

### ISSUE THREAD

**Issue by simontseng** [crossfilter/reductio#52]
is it possible for a complete example of how to use groupAll function

**Comment by esjewett** [comment]
Can you let me know what is missing from the example in the documentation? It looks fairly complete to me.

That said, you shouldn't use reductio's groupAll as it is redundant with the native array dimension functionality in Crossfilter 1.4. The new functionality is faster and should receive more attention and bug fixes. You can read about that here: https://github.com/crossfilter/crossfilter/wiki/API-Reference#dimension_with_arrays
